name: lacework-iac-example
# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the "main" branch
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    # A workflow run is made up of one or more jobs that can run sequentially or in parallel

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

jobs:
   Lacework-Scanner:
    # The type of runner that the job will run on
      runs-on: ubuntu-24.04
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout Code
          uses: actions/checkout@v3
        - name: Lacework IAC Scan
          env:
            LW_ACCOUNT: ${{ secrets.LW_ACCOUNT }}
            LW_API_KEY: ${{ secrets.LW_API_KEY }}
            LW_API_SECRET: ${{ secrets.LW_API_SECRET }}
          run: |
            # Setup
            env | grep "GITHUB_\|LW_\|CI_" > env.list
            echo "WORKSPACE=src" >> env.list
            cat env.list
            # Run the Scan
            docker run --debug --env-file env.list -v "$(pwd):/app/src" -w /app/src lacework/codesec:stable lacework iac scan --directory=.
