name: lacework-iac-scan-json-report

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write
  actions: read

jobs:
  Lacework-Scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Lacework IaC Scan
        id: laceworkscan
        env:
          LW_ACCOUNT: ${{ secrets.LW_ACCOUNT }}
          LW_API_KEY: ${{ secrets.LW_API_KEY }}
          LW_API_SECRET: ${{ secrets.LW_API_SECRET }}
        run: |
          # Setup
          env | grep "GITHUB_\|LW_\|CI_" > env.list    # Set Lacework and other secrets
          echo "WORKSPACE=src" >> env.list
          cat env.list
          # Run the Scan
          docker run --env-file env.list -v "$(pwd):/app/src" lacework/codesec:stable lacework iac scan
          
          



